# Use the official Node.js image as the build environment
FROM node:16 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./auto-client/package*.json ./

# Set npm timeout
RUN npm config set timeout 60000

# Install dependencies
RUN npm install --force

# Copy the rest of your application code
COPY ./auto-client/ .

# Build the application
RUN npm run build --prod

# Use the official Nginx image to serve the application
FROM nginx:alpine

# Copy the build output to Nginx's html directory
COPY --from=build /app/dist/auto-client /usr/share/nginx/html

# Expose the port Nginx is running on
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
