version: '3.8'
services:
  angular:
    build:
      context: ./
      dockerfile: dockerfile-client
    container_name: angular-app
    ports:
      - "8080:80"
    # volumes:
    #   - ./angular:/usr/src/app
    stdin_open: true
    tty: true
    depends_on:
      - api
   # command: nginx -g 'daemon off;'  # Start Nginx directly
    # networks:
    #   - app-network

  api:
    build:
      context: ./
      dockerfile: dockerfile-api
    container_name: api
    volumes:
      - ./php:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    # networks:
    #   - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: WAwi5697
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    # networks:
    #   - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: WAwi5697
    ports:
      - "8888:80"
    depends_on:
      - mysql
    # networks:
    #   - app-network

volumes:
  mysql-data:

networks:
  app-network:
