# Use the official PHP 8.2 image
FROM php:8.2-apache

# Set the working directory
WORKDIR /var/www/html

# Install system dependencies, FFmpeg, and mysqli
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    ffmpeg \
    && docker-php-ext-install zip mysqli pdo pdo_mysql \
    && docker-php-ext-enable mysqli

# Install Composer
COPY --from=composer:2.2 /usr/bin/composer /usr/local/bin/composer

# Copy the API code
COPY API/ .

# Install Composer dependencies
RUN composer install

# Copy custom Apache config
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

# Create the tmp directory and set proper permissions
RUN mkdir -p /var/www/html/tmp && \
    chown -R www-data:www-data /var/www/html/tmp && \
    chmod -R 775 /var/www/html/tmp

# Change ownership of /var/www/html to www-data
RUN chown -R www-data:www-data /var/www/html



# Enable the site and restart Apache
RUN a2ensite 000-default.conf



# Expose port 80
EXPOSE 80
