# Stage 1: Build Angular application
FROM node:18-alpine AS build

# Set working directory
WORKDIR /app

# Copy the package.json and package-lock.json to install dependencies
COPY ./angular/package.json ./
COPY ./angular/package-lock.json ./

# Install dependencies (use production mode to skip devDependencies if desired)
RUN npm ci --only=production --force

# Copy all the Angular project files
COPY ./auto-client/ ./

# Build the Angular app in production mode
RUN npm run build -- --configuration production

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

# Copy built Angular files from the previous stage to the Nginx html directory
COPY --from=build /app/dist/auto-client /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
